[package]
name = "bitcode-chain"
version = "0.1.0"
authors = ["Your Name <you@example.com>"]
edition = "2021"
description = "A modular blockchain written in Rust with PoW, smart contracts, and CLI/Web UI"
license = "MIT"
homepage = "https://github.com/yourname/bitcode-chain"
repository = "https://github.com/yourname/bitcode-chain"
documentation = "https://docs.rs/bitcode-chain"
readme = "README.md"
keywords = ["blockchain", "rust", "smart-contracts", "crypto"]
categories = ["cryptography", "network-programming", "wasm"]

[dependencies]
...

