[package]
name = "bitcode-node"
version = "0.1.0"
edition = "2021"
authors = ["Aditya <your@email.com>"]
description = "Bitcode Blockchain: modular Rust blockchain with P2P, CLI, dashboard, WASM contracts, and faucet mining"
license = "MIT"
repository = "https://github.com/bitcode-org/bitcode-blockchain"
keywords = ["blockchain", "rust", "p2p", "crypto", "wasm"]
categories = ["cryptography", "network-programming", "command-line-utilities"]
readme = "README.md"
homepage = "https://github.com/bitcode-org/bitcode-blockchain"
documentation = "https://docs.rs/bitcode-node"
build = "build.rs"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.10"
rand = "0.8"
base64 = "0.21"
tiny_http = "0.12"
ed25519-dalek = { version = "1.0", features = ["serde"] }
urlencoding = "2.1"
wasmer = "4.2.4"

[dev-dependencies]
clap = { version = "4.4", features = ["derive"] }

[[bin]]
name = "bitcode-node"
path = "src/main.rs"

[[example]]
name = "wallet"
path = "src/bin/wallet.rs"

[[example]]
name = "faucet"
path = "src/bin/faucet.rs"

[dependencies]
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
wasmer = "2.3" # or similar for WASM support
warp = "0.3"   # for Web UI
clap = "4.0"   # CLI parsing
log = "0.4"
env_logger = "0.10"
sha2 = "0.10"
serde = { version = "1.0", features = ["derive"] }
hex = "0.4"
k256 = { version = "0.13", features = ["ecdsa"] }
sha2 = "0.10"
rand_core = "0.6"
hex = "0.4"
wasmer = "4.2.5" # or latest stable




