[package]
name = "bitcode-chain"
version = "0.1.0"
edition = "2021"
description = "Bitcode Blockchain - Rust-based modular blockchain"
authors = ["Aditya"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tiny_http = "0.12"
ed25519-dalek = "1"
base64 = "0.21"
rand = "0.8"
md5 = "0.7"
urlencoding = "2"
tungstenite = "0.20"
wasmtime = "13"
